travel = ['Travel_Rarely', 'Travel_Frequently', 'Non-Travel']
department = ['Sales', 'Research & Development', 'Human Resources']
edu = ['College', 'Below College', 'Master', 'Doctor','Bachelor']
edu_field = ['Life Sciences', 'Other', 'Medical', 'Marketing', 'Technical Degree', 'Human Resources']
gender = ['Female', 'Male']
job_level = [1,2,3,4,5]
job_role = ['Healthcare Representative', 'Research Scientist', 'Sales Executive', 'Human Resources', 'Research Director', 'Laboratory Technician',
 'Manufacturing Director', 'Sales Representative', 'Manager']
marital = ['Married', 'Single', 'Divorced']
stock_option = [0,1,2,3]
environment = [1.0,2.0,3.0,4.0]
job_satisf = [1.0,2.0,3.0,4.0]
work_life = [1.0,2.0,3.0,4.0]
job_involve = [1.0,2.0,3.0,4.0]
performance= [1.0,2.0,3.0,4.0]